"""Postgres maintenance helpers (plano 29 · Eixo C).

``repair_postgres_sequences`` sobreviveu à remoção do ``db/migration_postgres``
(o caminho SQLite → Postgres morreu com o Postgres-only): continua exposto no
endpoint ``POST /api/admin/repair-sequences`` para recuperar sequências após
imports manuais de dados.
"""

from __future__ import annotations

from sqlalchemy import inspect
from sqlalchemy import text as sa_text
from sqlalchemy.engine import Engine


def repair_postgres_sequences(engine: Engine) -> dict[str, int]:
    """Re-anchor every Postgres sequence to ``MAX(<pk>)`` of its table.

    An explicit value supplied to an IDENTITY column does NOT advance the
    underlying sequence — so after a manual data import the next implicit
    INSERT tries to reuse an existing id and hits a unique-constraint
    violation.

    Walks every table with a single-column integer primary key, asks Postgres
    for the bound sequence via ``pg_get_serial_sequence`` (works for both
    classic ``SERIAL`` columns and modern ``GENERATED BY DEFAULT AS IDENTITY``
    columns) and calls ``setval`` with the current ``MAX(id)``. Returns a
    ``{table: new_value}`` map for telemetry.

    Idempotent and safe to call repeatedly.
    """
    if engine.dialect.name != "postgresql":
        return {}

    insp = inspect(engine)
    fixed: dict[str, int] = {}

    with engine.begin() as conn:
        for table_name in insp.get_table_names():
            if table_name == "alembic_version":
                continue
            pks = insp.get_pk_constraint(table_name).get("constrained_columns") or []
            if len(pks) != 1:
                continue  # composite PK — no sequence to repair
            pk_col = pks[0]
            cols = {c["name"]: c for c in insp.get_columns(table_name)}
            col_def = cols.get(pk_col)
            if col_def is None:
                continue
            # Only integer PKs have sequences. Skip TEXT PKs like ``config.key``.
            type_repr = str(col_def["type"]).upper()
            if "INT" not in type_repr:
                continue

            seq_name = conn.execute(
                sa_text("SELECT pg_get_serial_sequence(:t, :c)"),
                {"t": table_name, "c": pk_col},
            ).scalar()
            if not seq_name:
                continue  # column isn't bound to a sequence (manual id only)

            max_id = conn.execute(
                sa_text(f'SELECT COALESCE(MAX("{pk_col}"), 0) FROM "{table_name}"')
            ).scalar() or 0

            # ``setval(seq, n, true)`` — next nextval() returns n+1. When the
            # table is empty we pass 1 with ``is_called=false`` so the first
            # implicit insert still starts at 1.
            if max_id > 0:
                conn.execute(
                    sa_text("SELECT setval(:s, :v, true)"),
                    {"s": seq_name, "v": int(max_id)},
                )
            else:
                conn.execute(
                    sa_text("SELECT setval(:s, 1, false)"),
                    {"s": seq_name},
                )
            fixed[table_name] = int(max_id)

    return fixed
